#!/bin/sh

### BEGIN INIT INFO
# Provides:          waterd
# Required-Start:    $remote_fs $syslog $local_fs $network
# Required-Stop:     $remote_fs $syslog $local_fs $network
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts Water Server daemon
# Description:       This script runs the waterd service written
#                    by Lukasz for x. Mirek
### END INIT INFO

# Start the water daemon.

app=/usr/bin/waterServer
appconf=/etc/waterServer/config.ini
logconf=/etc/waterServer/log.ini
pidfile=/var/run/waterServer.pid

#trap "" 1
#trap "" 15

test -f $app || exit 0

. /lib/lsb/init-functions

start()
{
    log_daemon_msg "Starting water server"

    $app $appconf $logconf
    if [ $? != 0 ]; then
        log_end_msg 1
        exit 1
    else
        log_end_msg 0
    fi
}

stop()
{
    log_daemon_msg "Stopping water server"
    if [ -e $pidfile ]; then 
		cat $pidfile | xargs kill -INT
		RETVAL=$?
	else
		echo "not running"
		RETVAL=1
    fi

    if [ $RETVAL != 0 ]; then
        log_end_msg 1
        exit 1
    else
        log_end_msg 0
    fi
}


restart() {
    stop
    start
}

reload() {
    restart
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        $1
        ;;    
    *)
        echo $"Usage: $0 {start|stop|restart|reload}"
        exit 1
	;;
esac

exit 0
